# Generated by Django 4.2.6 on 2023-10-31 20:23
# Generated by Django 4.2.6 on 2023-10-31 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('img', models.ImageField(blank=True, upload_to='uploads', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Marketapp.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('number', models.IntegerField(auto_created=True, verbose_name='Номер заказа')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orders_date', models.DateTimeField(verbose_name='Дата')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('payment_type', models.CharField(max_length=20, verbose_name='Способ оплаты')),
                ('delivery_type', models.CharField(max_length=20, verbose_name='Способ доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('cost', models.FloatField(blank=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена и размер',
                'verbose_name_plural': 'Цены и размеры',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('measure', models.CharField(max_length=20, verbose_name='Ед.Измерения')),
                ('unit_cost', models.FloatField(verbose_name='Цена за единицу')),
                ('expiring_date', models.CharField(max_length=20, verbose_name='Срок годности')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('number_of_seats', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('availability', models.CharField(blank=True, choices=[('A', 'Доступен'), ('B', 'Забронирован')], max_length=1, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('birth_date', models.DateField(verbose_name='Дата рождение')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='TableOccupation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Начало бронирования')),
                ('end_time', models.DateTimeField(verbose_name='Конец бронирования')),
                ('id_table', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Marketapp.tables', verbose_name='Столик')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('id_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketapp.dishes', verbose_name='Блюдо')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketapp.orders', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Состав заказа',
                'verbose_name_plural': 'Состав заказов',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('measure', models.CharField(max_length=20, verbose_name='Ед.Измерения')),
                ('id_dishes', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Marketapp.dishes', verbose_name='Блюдо')),
                ('id_product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Marketapp.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('telephone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('id_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Marketapp.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='dishes',
            name='prices',
            field=models.ManyToManyField(blank=True, to='Marketapp.price', verbose_name='Цены/Размеры'),
        ),
        migrations.CreateModel(
            name='DeliveriesToMarket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(max_length=50, verbose_name='Поставщик')),
                ('expires', models.DateField(verbose_name='Истечение срока')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('cost', models.FloatField(verbose_name='Сумма')),
                ('status', models.CharField(max_length=30, verbose_name='Статус')),
                ('id_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Marketapp.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_level', models.IntegerField(verbose_name='Уровень доступа')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketapp.users', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
    ]
