# Generated by Django 4.2.6 on 2023-10-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishesOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('cost', models.FloatField(blank=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена и размер',
                'verbose_name_plural': 'Цены и размеры',
            },
        ),
        migrations.AddField(
            model_name='dishes',
            name='options',
            field=models.ManyToManyField(blank=True, to='Marketapp.dishesoptions', verbose_name='Опции'),
        ),
    ]
