# Generated by Django 4.2.6 on 2023-10-31 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketapp', '0002_dishesoptions_dishes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishesoptions',
            options={'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AlterField(
            model_name='dishes',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Marketapp.dishes', to_field='name', verbose_name='Имя'),
        ),
    ]
