# Generated by Django 4.2.6 on 2023-11-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketapp', '0004_alter_price_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'ordering': ['id'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['id'], 'verbose_name': 'Цена и размер', 'verbose_name_plural': 'Цены и размеры'},
        ),
        migrations.AddField(
            model_name='price',
            name='weight',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вес'),
        ),
    ]
