# Generated by Django 4.2.6 on 2023-11-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketapp', '0005_alter_dishes_options_alter_price_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishesoptions',
            name='weight_changes',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение веса'),
        ),
        migrations.AlterField(
            model_name='dishesoptions',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
