# Generated by Django 4.2.6 on 2023-11-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketapp', '0006_dishesoptions_weight_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesoptions',
            name='weight_changes',
            field=models.FloatField(blank=True, null=True, verbose_name='Изменение веса в %'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='id_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='Marketapp.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='measure',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ед.Измерения'),
        ),
    ]
